server:
    address: 0.0.0.0
    #context-path: /beerhouse
    port: 8080
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE";
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                format_sql: true
                show_sql: false
                type: 'trace '
                use_sql_comments: true
    cache:
        type: "none"